/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NewIcons {
  NewIcons._();

  static const _kFontFam = 'NewIcons';
  static const String? _kFontPkg = null;

  static const IconData cellphone_basic = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_heart_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_outline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_outline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Settings = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Shopify = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Bag_outlined = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Wallet_outlined = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Heart_outlined = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Home_outlined = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Home = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_hreat = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Heart = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Bag = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Wallet = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Menu_open = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Menu_close = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Search_outlined = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified = IconData(0xf3a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xf3a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData government = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downArrow = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowUp = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bin = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);






}
